CREATE TABLE TT_LOGIN
(
  USERNAME VARCHAR(20) primary key,
  PASSW VARCHAR(20),
  HOSTNAME VARCHAR(20),
  SID VARCHAR(20)
)

--Set ID_NHANVIEN_TANG
Create Sequence ID_NHANVIEN_TANG
Start with 1
Minvalue 1
Increment by 1
Cache 20;
-- Tao bang NHANVIEN
CREATE TABLE NHANVIEN
(
  ID NUMBER DEFAULT ON NULL ID_NHANVIEN_TANG.nextval,
  MANV VARCHAR2(10) PRIMARY KEY,
  TENNV NVARCHAR2(50),
  NGAYSINH DATE,
  GIOITINH NVARCHAR2(5),
  NGAYVAOLAM DATE,
  DIACHI NVARCHAR2(100),
  SODT VARCHAR2(11),
  LUONG DECIMAL(18, 2)
);
commit;

--Set ID_KHAHHANG_TANG 
Create Sequence ID_KHACHHANG_TANG
Start with 1
Minvalue 1
Increment by 1
Cache 20;
-- Tao bang KHACHHANG
CREATE TABLE KHACHHANG
(
  ID NUMBER DEFAULT ON NULL ID_KHACHHANG_TANG.nextval,
  MAKH VARCHAR2(10) PRIMARY KEY,
  TENKH NVARCHAR2(50),
  GIOITINH NVARCHAR2(5),
  DIACHI NVARCHAR2(100),
  SODT VARCHAR2(11)
);
commit;

--Set ID_NHACUNGCAP_TANG 
Create Sequence ID_NHACUNGCAP_TANG
Start with 1
Minvalue 1
Increment by 1
Cache 20;
-- Tao bang NHACUNGCAP
CREATE TABLE NHACUNGCAP
(
  ID NUMBER DEFAULT ON NULL ID_NHACUNGCAP_TANG.nextval,
  MANCC VARCHAR2(10) PRIMARY KEY,
  TENNCC NVARCHAR2(100),
  SODT VARCHAR(11),
  DIACHI NVARCHAR2(100)
);
commit;

--Set ID_THUONGHIEU_TANG 
Create Sequence ID_THUONGHIEU_TANG
Start with 1
Minvalue 1
Increment by 1
Cache 20;
-- Tao bang THUONGHIEU
CREATE TABLE THUONGHIEU
(
  ID NUMBER DEFAULT ON NULL ID_THUONGHIEU_TANG.nextval,
  MATH VARCHAR2(10) PRIMARY KEY,
  TENTH NVARCHAR2(100)
);
commit;

--Set ID_THIETBI_TANG 
Create Sequence ID_THIETBI_TANG
Start with 1
Minvalue 1
Increment by 1
Cache 20;
-- Tao bang THIETBI
CREATE TABLE THIETBI
( 
  ID NUMBER DEFAULT ON NULL ID_THIETBI_TANG.nextval,
  HINHANH Blob,
  MATB VARCHAR(10) PRIMARY KEY,
  TENTB VARCHAR(100),
  DONGIANHAP DECIMAL(18,2),
  DONGIABAN DECIMAL(18,2),
  SOLUONG INT,
  MOTA NVARCHAR2(100),
  MATH VARCHAR2(10) NOT NULL,
  MANCC VARCHAR2(10) NOT NULL,
  CONSTRAINT FK_MATH_THUONGHIEU FOREIGN KEY(MATH) REFERENCES THUONGHIEU(MATH),
  CONSTRAINT FK_MANCC_NHACUNGCAP FOREIGN KEY(MANCC) REFERENCES NHACUNGCAP(MANCC)
);
commit;

--Set ID_HOADONBAN_TANG 
Create Sequence ID_HOADONBAN_TANG
Start with 1
Minvalue 1
Increment by 1
Cache 20;
-- Tao bang HOADONBAN
CREATE TABLE HOADONBAN
(
  ID NUMBER DEFAULT ON NULL ID_HOADONBAN_TANG.nextval,
  MAHDB VARCHAR(15) PRIMARY KEY,
  MANV VARCHAR2(10) NOT NULL,
  MAKH VARCHAR2(10) NOT NULL,
  NGAYBAN DATE,
  TONGTIEN DECIMAL(18,2),
  CONSTRAINT FK_MANV_NHANVIEN FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV),
  CONSTRAINT FK_MAKH_KHACHHANG FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH)
);
commit;
-- Tao bang CT_HOADONBAN
CREATE TABLE CT_HOADONBAN
(
  MAHDB VARCHAR2(15) NOT NULL,
  MATB VARCHAR2(10) NOT NULL,
  TENTHIETBI NVARCHAR2(100),
  DONGIABAN DECIMAL(18,2),
  SLBAN INT,
  THANHTIEN DECIMAL(18,2),
  CONSTRAINT PK_CTHD PRIMARY KEY(MAHDB, MATB),
  CONSTRAINT FK_MATB_THIETBI FOREIGN KEY(MATB) REFERENCES THIETBI(MATB),
  CONSTRAINT FK_MAHDB_HOADONBAN FOREIGN KEY(MAHDB) REFERENCES HOADONBAN(MAHDB)
);
commit;

--Set ID_HOADONNHAP_TANG 
Create Sequence ID_HOADONNHAP_TANG
Start with 1
Minvalue 1
Increment by 1
Cache 20;
-- Tao bang HOADONNHAP
CREATE TABLE HOADONNHAP
(
  ID NUMBER DEFAULT ON NULL ID_HOADONNHAP_TANG.nextval,
  MAHDN VARCHAR(15) PRIMARY KEY,
  MANV VARCHAR2(10) NOT NULL,
  MANCC VARCHAR2(10) NOT NULL,
  NGAYNHAP DATE,
  TONGTIEN DECIMAL(18,2),
  CONSTRAINT FK_MANV_NHANVIEN1 FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV),
  CONSTRAINT FK_MANCC_NHACUNGCAP1 FOREIGN KEY(MANCC) REFERENCES NHACUNGCAP(MANCC)
);
commit;

-- Tao bang CT_HOADONNHAP
CREATE TABLE CT_HOADONNHAP
(
  MAHDN VARCHAR(15) NOT NULL,
  MATB VARCHAR(10) NOT NULL,
  TENTHIETBI NVARCHAR2(100),
  DONGIANHAP DECIMAL(18,2),
  SLNHAP INT,
  THANHTIEN DECIMAL(18,2),
  CONSTRAINT PK_CTHDN PRIMARY KEY(MAHDN, MATB),
  CONSTRAINT FK_MAHDN_HOADONNHAP FOREIGN KEY(MAHDN) REFERENCES HOADONNHAP(MAHDN),
  CONSTRAINT FK_MATB_THIETBI1 FOREIGN KEY(MATB) REFERENCES THIETBI(MATB)
);
commit;
--Them du lieu bang NHANVIEN(ID, MANV, TENNV, NGAYSINH, GIOITINH, NGAYVAOLAM, DIACHI, SODT, LUONG)
INSERT INTO NHANVIEN VALUES(NULL, 'NV001', 'Huynh Nhat Tan', '13-AUG-2001', 'Nam', '10-AUG-2021', 'Ben Tre', '0354479948', 6000000);
INSERT INTO NHANVIEN VALUES(NULL, 'NV002', 'Tran Minh Tan', '05-MAY-2001', 'Nam', '12-AUG-2021', 'Long An', '0354479999', 6100000);
INSERT INTO NHANVIEN VALUES(NULL, 'NV003', 'Nguyen Le Hoang Duy', '04-JAN-2001', 'Nam', '15-AUG-2021', 'Donng Nai', '0354478989', 6200000);
INSERT INTO NHANVIEN VALUES(NULL, 'NV006', 'Huynh Nhat Tan', '13-AUG-2001', 'Nam', '10-AUG-2021', 'Ben Tre', '0354479948', 6000000);
COMMIT;
select * from khachhang
--Them du lieu bang KHACHHANG(ID, MAKH, TENKH, GIOITINH, DIACHI, SODT)
INSERT INTO KHACHHANG VALUES(NULL, 'KH001', 'Lê Thi Hang', 'Nu', 'Bình D??ng', '0123456565');
INSERT INTO KHACHHANG VALUES(NULL, 'KH002', 'Nguyen Van Binh', 'Nam', 'TP HCM', '0123436566');
INSERT INTO KHACHHANG VALUES(NULL, 'KH003', 'Lâm Thi Nhi', 'Nu', 'Bình Phuoc', '0123466515');
COMMIT;
SELECT * FROM KHACHHANG
--Them du lieu bang NHACUNGCAP(ID, MANCC, TENNCC, SODT, DIACHI)
INSERT INTO NHACUNGCAP VALUES(NULL, 'NCC01', 'CTY DIEN MAY BEN TRE', '0000111900', 'Ben Tre');
INSERT INTO NHACUNGCAP VALUES(NULL, 'NCC02', 'CTY DIEN MAY LONG AN', '0000111901', 'Long An');
INSERT INTO NHACUNGCAP VALUES(NULL, 'NCC03', 'CTY DIEN MAY TIEN GIANG', '0000111902', 'Tien Giang');
COMMIT;
SELECT * FROM NHACUNGCAP
--Them du lieu bang THUONGHIEU(ID, MATH, TENTH)
INSERT INTO THUONGHIEU VALUES(NULL, 'TH001', 'SAMSUNG');
INSERT INTO THUONGHIEU VALUES(NULL, 'TH002', 'NOKIA');
INSERT INTO THUONGHIEU VALUES(NULL, 'TH003', 'OPPO');
INSERT INTO THUONGHIEU VALUES(NULL, 'TH004', 'APPLE');
INSERT INTO THUONGHIEU VALUES(NULL, 'TH005', 'XIAOMI');
INSERT INTO THUONGHIEU VALUES(NULL, 'TH006', 'HTC');
INSERT INTO THUONGHIEU VALUES(NULL, 'TH007', 'SONY');
COMMIT;
SELECT * FROM THUONGHIEU
--Them du lieu bang THIETBI(ID, HINHANH, MATB, TENTB, DONGIANHAP, DONGIABAN, SOLUONG, MOTA, MATH, MANCC)
INSERT INTO THIETBI VALUES(NULL, utl_raw.cast_to_raw('C:\Users\Admin\Documents\CongNgheJava\CuaHangDienThoai\src\HinhAnh'), 'TB001', 'Samsung S8', 7000, 9000, 0, 'SamSung GaLaXy S8 64GB', 'TH001', 'NCC01');
INSERT INTO THIETBI VALUES(NULL, Utl_Raw.Cast_To_Raw('C:\Users\Admin\Documents\CongNgheJava\CuaHangDienThoai\src\HinhAnh'), 'TB002', 'iPhone 8s', 8800, 11000, 0, 'Iphone 8', 'TH004', 'NCC01');
INSERT INTO THIETBI VALUES(NULL, Utl_Raw.Cast_To_Raw('C:\Users\Admin\Documents\CongNgheJava\CuaHangDienThoai\src\HinhAnh'), 'TB003',  'HTC One Me', 4000, 5800, 45, 'HTC One Me', 'TH006', 'NCC02');
INSERT INTO THIETBI VALUES(NULL, Utl_Raw.Cast_To_Raw('C:\Users\Admin\Documents\CongNgheJava\CuaHangDienThoai\src\HinhAnh'), 'TB004', 'Sony Xperia 1', 11000, 12000, 10, 'Sony Xperia 1 512GB', 'TH007', 'NCC01');
INSERT INTO THIETBI VALUES(NULL, Utl_Raw.Cast_To_Raw('C:\Users\Admin\Documents\CongNgheJava\CuaHangDienThoai\src\HinhAnh'), 'TB005', 'SamSung GaLaXy S9', 42000, 52000, 147, 'SamSung GaLaXy S9 128GB', 'TH001', 'NCC03');
INSERT INTO THIETBI VALUES(NULL, Utl_Raw.Cast_To_Raw('C:\Users\Admin\Documents\CongNgheJava\CuaHangDienThoai\src\HinhAnh'), 'TB006', 'Iphone X 512GB', 120000, 130000, 50, 'Iphone X 512GB ', 'TH004', 'NCC02');
INSERT INTO THIETBI VALUES(NULL, Utl_Raw.Cast_To_Raw('C:\Users\Admin\Documents\CongNgheJava\CuaHangDienThoai\src\HinhAnh'), 'TB007', 'Oppo Find 5', 2000, 2500, 100, 'Oppo Find 5 ', 'TH003', 'NCC03');
COMMIT;
SELECT * FROM THIETBI
--Them du lieu bang HOADONBAN(ID, MAHDB, MANV, MAKH, NGAYBAN, TONGTIEN)
INSERT INTO HOADONBAN VALUES(NULL, 'HDB001', 'NV001', 'KH001', '01-OCT-2021', 0);
INSERT INTO HOADONBAN VALUES(NULL, 'HDB002', 'NV001', 'KH002', '02-OCT-2021', 0);
INSERT INTO HOADONBAN VALUES(NULL, 'HDB003', 'NV002', 'KH003', '03-OCT-2021', 0);
COMMIT;

--Them du lieu bang CT_HOADONBAN(MAHDB, MATB, TENTHIETBI, DONGIABAN, SLBAN, THANHTIEN)
INSERT INTO CT_HOADONBAN VALUES('HDB001', 'TB002', 'iPhone 8s', 11000, 2, 22000);
INSERT INTO CT_HOADONBAN VALUES('HDB002', 'TB001', 'Samsung S8', 9000, 2, 18000);
INSERT INTO CT_HOADONBAN VALUES('HDB003', 'TB002', 'iPhone 8s', 9000, 3, 27000);
COMMIT;

--Them du lieu bang HOADONNHAP(ID, MAHDN, MANV, MANCC, NGAYNHAP, TONGTIEN)
INSERT INTO HOADONNHAP VALUES(NULL, 'HDN001', 'NV001', 'NCC01', '01-OCT-2021', 0);
INSERT INTO HOADONNHAP VALUES(NULL, 'HDN002', 'NV002', 'NCC02', '04-OCT-2021', 0);
INSERT INTO HOADONNHAP VALUES(NULL, 'HDN003', 'NV001', 'NCC03', '05-OCT-2021', 0);
COMMIT;

--Them du lieu bang CT_HOADONNHAP(MAHDN, MATB, TENTHIETBI, DONGIANHAP, SLNHAP, THANHTIEN)
INSERT INTO CT_HOADONNHAP VALUES('HDN001', 'TB003', 'HTC One Me', 4000, 20, 80000);
INSERT INTO CT_HOADONNHAP VALUES('HDN002', 'TB002', 'iPhone 8s', 8800, 10, 88000);
INSERT INTO CT_HOADONNHAP VALUES('HDN003', 'TB004', 'Sony Xperia 1', 11000, 10, 110000);
COMMIT;

--1. Viet thu tuc xem thong tin Tablespace
CREATE OR REPLACE PROCEDURE XEM_TABLESPACE IS
BEGIN
    SELECT Tablespace_Name, Block_Size, Initial_Extent, Status from Dba_Tablespaces
END;
--THUC THI
EXECUTE XEM_TABLESPACE;
--XOA NHOM QUYEN             sai
  CREATE OR REPLACE PROCEDURE XoaQuyen
  (P_NAME_QUYEN IN  VARCHAR2 )
	AS
	BEGIN
   EXECUTE IMMEDIATE  'DROP ROLE' || P_NAME_QUYEN;
	END ; 
  --THUC THI
  
	EXECUTE XoaQuyen('QUYEN1');
  
  DROP ROLE QUYEN1;
  CREATE ROLE QUYEN1;

/*--------------------------------------CAC THU TUC INSERT, UPDATE, DELETE DU LIEU-----------------------------------*/
-------------------------TABLE DBO.[KHACHHANG]--------------------------------
--Thu tuc INSERT INTO KHACHHANG
CREATE OR REPLACE PROCEDURE INSERT_KHACHHANG
(
  P_MAKH IN HR.KHACHHANG.MAKH%TYPE,
  P_TENKH IN HR.KHACHHANG.TENKH%TYPE,
  P_GIOITINH IN HR.KHACHHANG.GIOITINH%TYPE,
  P_DIACHI IN HR.KHACHHANG.DIACHI%TYPE,
  P_SODT IN HR.KHACHHANG.SODT%TYPE
)
IS
BEGIN
  INSERT INTO HR.KHACHHANG
  VALUES(NULL, P_MAKH, P_TENKH, P_GIOITINH, P_DIACHI, P_SODT);
  COMMIT;
END;
/

--THUC THI INSERT_KHACHHANG
EXECUTE INSERT_KHACHHANG('KH005', 'Nguyen Van A', 'Nam', 'Ben Tre', '0354479999');
select * from khachhang

--Thu tuc UPDATE KHACHHANG
CREATE OR REPLACE PROCEDURE UPDATE_KHACHHANG
(
  P_ID IN HR.KHACHHANG.ID%TYPE,
  P_MAKH IN HR.KHACHHANG.MAKH%TYPE,
  P_TENKH IN HR.KHACHHANG.TENKH%TYPE,
  P_GIOITINH IN HR.KHACHHANG.GIOITINH%TYPE,
  P_DIACHI IN HR.KHACHHANG.DIACHI%TYPE,
  P_SODT IN HR.KHACHHANG.SODT%TYPE
)
IS
BEGIN
  UPDATE HR.KHACHHANG
  SET ID=P_ID, TENKH = P_TENKH, GIOITINH = P_GIOITINH, DIACHI = P_DIACHI, SODT = P_SODT
  WHERE MAKH = P_MAKH;
  COMMIT;
END;
/
select * from nhanvien
--Thu tuc DELETE KHACHHANG
CREATE OR REPLACE PROCEDURE DELETE_KHACHHANG(P_ID IN HR.KHACHHANG.ID%TYPE)
IS
BEGIN
  DELETE HR.KHACHHANG WHERE ID = P_ID;
  COMMIT;
END;
/

-------------------------TABLE DBO.[NHANVIEN]--------------------------------
--/Thu tuc INSERT INTO NHANVIEN/s
CREATE OR REPLACE PROCEDURE INSERT_NHANVIEN
(
  P_MANV IN HR.NHANVIEN.MANV%TYPE,
  P_TENNV IN HR.NHANVIEN.TENNV%TYPE,
  P_NGAYSINH IN HR.NHANVIEN.NGAYSINH%TYPE,
  P_GIOITINH IN HR.NHANVIEN.GIOITINH%TYPE,
  P_NGAYVAOLAM IN HR.NHANVIEN.NGAYVAOLAM%TYPE,
  P_DIACHI IN HR.NHANVIEN.DIACHI%TYPE,
  P_SODT IN HR.NHANVIEN.SODT%TYPE,
  P_LUONG IN HR.NHANVIEN.LUONG%TYPE
)
IS 
BEGIN
  INSERT INTO HR.NHANVIEN
  VALUES(NULL, P_MANV, P_TENNV, P_NGAYSINH, P_GIOITINH, P_NGAYVAOLAM, P_DIACHI, P_SODT, P_LUONG);
  COMMIT;
END;
/

--Thu tuc UPDATE NHANVIEN
CREATE OR REPLACE PROCEDURE UPDATE_NHANVIEN
(
  P_ID IN HR.NHANVIEN.ID%TYPE,
  P_MANV IN HR.NHANVIEN.MANV%TYPE,
  P_TENNV IN HR.NHANVIEN.TENNV%TYPE,
  P_NGAYSINH IN HR.NHANVIEN.NGAYSINH%TYPE,
  P_GIOITINH IN HR.NHANVIEN.GIOITINH%TYPE,
  P_NGAYVAOLAM IN HR.NHANVIEN.NGAYVAOLAM%TYPE,
  P_DIACHI IN HR.NHANVIEN.DIACHI%TYPE,
  P_SODT IN HR.NHANVIEN.SODT%TYPE,
  P_LUONG IN HR.NHANVIEN.LUONG%TYPE
)
IS
BEGIN
  UPDATE HR.NHANVIEN
  SET ID = P_ID, TENNV = P_TENNV, NGAYSINH = P_NGAYSINH, GIOITINH = P_GIOITINH, 
      NGAYVAOLAM = P_NGAYVAOLAM, DIACHI = P_DIACHI, SODT = P_SODT, LUONG = P_LUONG
  WHERE MANV = P_MANV;
  COMMIT;
END;
/

--Thu tuc DELETE NHANVIEN
CREATE OR REPLACE PROCEDURE DELETE_NHANVIEN(P_ID IN HR.NHANVIEN.ID%TYPE)
IS
BEGIN
  DELETE HR.NHANVIEN WHERE ID = P_ID;
  COMMIT;
END;
/

-------------------------TABLE DBO.[THIETBI]--------------------------------
select * from THIETBI
CREATE OR REPLACE PROCEDURE INSERT_THIETBI
(
  P_HINHANH IN HR.THIETBI.HINHANH%TYPE,
  P_MATB IN HR.THIETBI.MATB%TYPE,
  P_TENTB IN HR.THIETBI.TENTB%TYPE,
  P_DONGIANHAP IN HR.THIETBI.DONGIANHAP%TYPE,
  P_DONGIABAN IN HR.THIETBI.DONGIABAN%TYPE,
  P_SOLUONG IN HR.THIETBI.SOLUONG%TYPE,
  P_MOTA IN HR.THIETBI.MOTA%TYPE,
  P_MATH IN HR.THIETBI.MATH%TYPE,
  P_MANCC IN HR.THIETBI.MANCC%TYPE
)
IS 
BEGIN
  INSERT INTO HR.THIETBI
  VALUES(NULL, P_HINHANH, P_MATB, P_TENTB, P_DONGIANHAP, P_DONGIABAN, P_SOLUONG, P_MOTA, P_MATH, P_MANCC);
  COMMIT;
END;
/

--Thu tuc UPDATE THIETBI
CREATE OR REPLACE PROCEDURE UPDATE_THIETBI
(
  P_ID IN HR.THIETBI.ID%TYPE,
  P_HINHANH IN HR.THIETBI.HINHANH%TYPE,
  P_MATB IN HR.THIETBI.MATB%TYPE,
  P_TENTB IN HR.THIETBI.TENTB%TYPE,
  P_DONGIANHAP IN HR.THIETBI.DONGIANHAP%TYPE,
  P_DONGIABAN IN HR.THIETBI.DONGIABAN%TYPE,
  P_SOLUONG IN HR.THIETBI.SOLUONG%TYPE,
  P_MOTA IN HR.THIETBI.MOTA%TYPE,
  P_MATH IN HR.THIETBI.MATH%TYPE,
  P_MANCC IN HR.THIETBI.MANCC%TYPE
)
IS
BEGIN
  UPDATE HR.THIETBI
  SET HINHANH = P_HINHANH, MATB = P_MATB, TENTB = P_TENTB, DONGIANHAP = P_DONGIANHAP, DONGIABAN = P_DONGIABAN,
      SOLUONG = P_SOLUONG, MOTA = P_MOTA, MATH = P_MATH, MANCC = P_MANCC
  WHERE ID = P_ID;
  COMMIT;
END;
/

--Thu tuc DELETE THIETBI
CREATE OR REPLACE PROCEDURE DELETE_THIETBI(P_ID IN HR.THIETBI.ID%TYPE)
IS
BEGIN
  DELETE HR.THIETBI WHERE ID = P_ID;
  COMMIT;
END;
/

-------------------------TABLE DBO.[NHACUNGCAP]--------------------------------
--Thu tuc INSERT INTO NHACUNGCAP
select * from nhacungcap
CREATE OR REPLACE PROCEDURE INSERT_NHACUNGCAP
(
  P_MANCC IN HR.NHACUNGCAP.MANCC%TYPE,
  P_TENNCC IN HR.NHACUNGCAP.TENNCC%TYPE,
  P_SODT IN HR.NHACUNGCAP.SODT%TYPE,
  P_DIACHI IN HR.NHACUNGCAP.DIACHI%TYPE
)
IS 
BEGIN
  INSERT INTO HR.NHACUNGCAP
  VALUES(NULL, P_MANCC, P_TENNCC, P_SODT, P_DIACHI);
  COMMIT;
END;
/

--Thu tuc UPDATE NHACUNGCAP
CREATE OR REPLACE PROCEDURE UPDATE_NHACUNGCAP
(
  P_ID IN HR.NHACUNGCAP.ID%TYPE,
  P_MANCC IN HR.NHACUNGCAP.MANCC%TYPE,
  P_TENNCC IN HR.NHACUNGCAP.TENNCC%TYPE,
  P_SODT IN HR.NHACUNGCAP.SODT%TYPE,
  P_DIACHI IN HR.NHACUNGCAP.DIACHI%TYPE
)
IS
BEGIN
  UPDATE HR.NHACUNGCAP
  SET ID = P_ID, TENNCC = P_TENNCC, SODT = P_SODT, DIACHI = P_DIACHI
  WHERE MANCC = P_MANCC;
  COMMIT;
END;
/

--Thu tuc DELETE NHACUNGCAP
CREATE OR REPLACE PROCEDURE DELETE_NHACUNGCAP(P_ID IN HR.NHACUNGCAP.ID%TYPE)
IS
BEGIN
  DELETE HR.NHACUNGCAP WHERE ID = P_ID;
  COMMIT;
END;
/

-------------------------TABLE DBO.[THUONGHIEU]--------------------------------
--Thu tuc INSERT INTO THUONGHIEU
select * from thuonghieu
CREATE OR REPLACE PROCEDURE INSERT_THUONGHIEU
(
  P_MATH IN HR.THUONGHIEU.MATH%TYPE,
  P_TENTH IN HR.THUONGHIEU.TENTH%TYPE
)
IS 
BEGIN
  INSERT INTO HR.THUONGHIEU
  VALUES(NULL, P_MATH, P_TENTH);
  COMMIT;
END;
/

--Thu tuc UPDATE THUONGHIEU
CREATE OR REPLACE PROCEDURE UPDATE_THUONGHIEU
(
  P_ID IN HR.THUONGHIEU.ID%TYPE,
  P_MATH IN HR.THUONGHIEU.MATH%TYPE,
  P_TENTH IN HR.THUONGHIEU.TENTH%TYPE
)
IS
BEGIN
  UPDATE HR.THUONGHIEU
  SET ID = P_ID, TENTH = P_TENTH
  WHERE MATH = P_MATH;
  COMMIT;
END;
/
SELECT * FROM THIETBI
--Thu tuc DELETE THUONGHIEU
CREATE OR REPLACE PROCEDURE DELETE_THUONGHIEU(P_ID IN HR.THUONGHIEU.ID%TYPE)
IS
BEGIN
  DELETE HR.THUONGHIEU WHERE ID = P_ID;
  COMMIT;
END;
/

-------------------------TABLE DBO.[HOADONBAN]--------------------------------
--Thu tuc INSERT INTO HOADONBAN
select * from HOADONBAN;
CREATE OR REPLACE PROCEDURE INSERT_HOADONBAN
(
  P_MAHDB IN HR.HOADONBAN.MAHDB%TYPE,
  P_MANV IN HR.HOADONBAN.MANV%TYPE,
  P_MAKH IN HR.HOADONBAN.MAKH%TYPE,
  P_NGAYBAN IN HR.HOADONBAN.NGAYBAN%TYPE,
  P_TONGTIEN IN HR.HOADONBAN.TONGTIEN%TYPE
)
IS 
BEGIN
  INSERT INTO HR.HOADONBAN
  VALUES(NULL, P_MAHDB, P_MANV, P_MAKH, P_NGAYBAN, P_TONGTIEN);
  COMMIT;
END;
/

--Thu tuc UPDATE HOADONBAN
CREATE OR REPLACE PROCEDURE UPDATE_HOADONBAN
(
  P_ID IN HR.HOADONBAN.ID%TYPE,
  P_MAHDB IN HR.HOADONBAN.MAHDB%TYPE,
  P_MANV IN HR.HOADONBAN.MANV%TYPE,
  P_MAKH IN HR.HOADONBAN.MAKH%TYPE,
  P_NGAYBAN IN HR.HOADONBAN.NGAYBAN%TYPE,
  P_TONGTIEN IN HR.HOADONBAN.TONGTIEN%TYPE
)
IS
BEGIN
  UPDATE HR.HOADONBAN
  SET MAHDB = P_MAHDB, MANV = P_MANV, MAKH = P_MAKH, NGAYBAN = P_NGAYBAN, TONGTIEN = P_TONGTIEN
  WHERE ID = P_ID;
  COMMIT;
END;
/

--Thu tuc DELETE HOADONBAN
CREATE OR REPLACE PROCEDURE DELETE_HOADONBAN(P_ID IN HR.HOADONBAN.ID%TYPE)
IS
BEGIN
  DELETE HR.HOADONBAN WHERE ID = P_ID;
  COMMIT;
END;
/

-------------------------TABLE DBO.[HOADONNHAP]--------------------------------
--Thu tuc INSERT INTO HOADONNHAP
SELECT * FROM HOADONNHAP;
CREATE OR REPLACE PROCEDURE INSERT_HOADONNHAP
(
  P_MAHDN IN HR.HOADONNHAP.MAHDN%TYPE,
  P_MANV IN HR.HOADONNHAP.MANV%TYPE,
  P_MANCC IN HR.HOADONNHAP.MANCC%TYPE,
  P_NGAYNHAP IN HR.HOADONNHAP.NGAYNHAP%TYPE,
  P_TONGTIEN IN HR.HOADONNHAP.TONGTIEN%TYPE
)
IS 
BEGIN
  INSERT INTO HR.HOADONNHAP
  VALUES(NULL, P_MAHDN, P_MANV, P_MANCC, P_NGAYNHAP, P_TONGTIEN);
  COMMIT;
END;
/

--Thu tuc UPDATE HOADONNHAP
CREATE OR REPLACE PROCEDURE UPDATE_HOADONNHAP
(
  P_ID IN HR.HOADONNHAP.ID%TYPE,
  P_MAHDN IN HR.HOADONNHAP.MAHDN%TYPE,
  P_MANV IN HR.HOADONNHAP.MANV%TYPE,
  P_MANCC IN HR.HOADONNHAP.MANCC%TYPE,
  P_NGAYNHAP IN HR.HOADONNHAP.NGAYNHAP%TYPE,
  P_TONGTIEN IN HR.HOADONNHAP.TONGTIEN%TYPE
)
IS
BEGIN
  UPDATE HR.HOADONNHAP
  SET MAHDN = P_MAHDN, MANV = P_MANV, MANCC = P_MANCC, NGAYNHAP = P_NGAYNHAP, TONGTIEN = P_TONGTIEN
  WHERE ID = P_ID;
  COMMIT;
END;
/

--Thu tuc DELETE HOADONNHAP
CREATE OR REPLACE PROCEDURE DELETE_HOADONNHAP(P_ID IN HR.HOADONNHAP.ID%TYPE)
IS
BEGIN
  DELETE HR.HOADONNHAP WHERE ID = P_ID;
  COMMIT;
END;
/

-------------------------TABLE DBO.[CT_HOADONBAN]--------------------------------
--Thu tuc INSERT INTO CT_HOADONBAN
SELECT * FROM CT_HOADONBAN;
CREATE OR REPLACE PROCEDURE INSERT_CT_HOADONBAN
(
  P_MAHDB IN HR.CT_HOADONBAN.MAHDB%TYPE,
  P_MATB IN HR.CT_HOADONBAN.MATB%TYPE,
  P_TENTHIETBI IN HR.CT_HOADONBAN.TENTHIETBI%TYPE,
  P_DONGIABAN IN HR.CT_HOADONBAN.DONGIABAN%TYPE,
  P_SLBAN IN HR.CT_HOADONBAN.SLBAN%TYPE,
  P_THANHTIEN IN HR.CT_HOADONBAN.THANHTIEN%TYPE
)
IS 
BEGIN
  INSERT INTO HR.CT_HOADONBAN
  VALUES(P_MAHDB, P_MATB, P_TENTHIETBI, P_DONGIABAN, P_SLBAN, P_THANHTIEN);
  COMMIT;
END;
/

--Thu tuc UPDATE CT_HOADONBAN
CREATE OR REPLACE PROCEDURE UPDATE_CT_HOADONBAN
(
  P_MAHDB IN HR.CT_HOADONBAN.MAHDB%TYPE,
  P_MATB IN HR.CT_HOADONBAN.MATB%TYPE,
  P_TENTHIETBI IN HR.CT_HOADONBAN.TENTHIETBI%TYPE,
  P_DONGIABAN IN HR.CT_HOADONBAN.DONGIABAN%TYPE,
  P_SLBAN IN HR.CT_HOADONBAN.SLBAN%TYPE,
  P_THANHTIEN IN HR.CT_HOADONBAN.THANHTIEN%TYPE
)
IS
BEGIN
  UPDATE HR.CT_HOADONBAN
  SET MAHDB = P_MAHDB, MATB = P_MATB, TENTHIETBI = P_TENTHIETBI,
      DONGIABAN = P_DONGIABAN, SLBAN = P_SLBAN, THANHTIEN = P_THANHTIEN
  WHERE MAHDB = P_MAHDB AND MATB = P_MATB;
  COMMIT;
END;
/

--Thu tuc DELETE CT_HOADONBAN
CREATE OR REPLACE PROCEDURE DELETE_CT_HOADONBAN
(P_MAHDB IN HR.CT_HOADONBAN.MAHDB%TYPE, P_MATB IN HR.CT_HOADONBAN.MATB%TYPE)
IS
BEGIN
  DELETE HR.CT_HOADONBAN WHERE MAHDB = P_MAHDB AND MATB = P_MATB;
  COMMIT;
END;
/

-------------------------TABLE DBO.[CT_HOADONNHAP]--------------------------------
--Thu tuc INSERT INTO CT_HOADONNHAP
SELECT * FROM CT_HOADONNHAP;
CREATE OR REPLACE PROCEDURE INSERT_CT_HOADONNHAP
(
  P_MAHDN IN HR.CT_HOADONNHAP.MAHDN%TYPE,
  P_MATB IN HR.CT_HOADONNHAP.MATB%TYPE,
  P_TENTHIETBI IN HR.CT_HOADONNHAP.TENTHIETBI%TYPE,
  P_DONGIANHAP IN HR.CT_HOADONNHAP.DONGIANHAP%TYPE,
  P_SLNHAP IN HR.CT_HOADONNHAP.SLNHAP%TYPE,
  P_THANHTIEN IN HR.CT_HOADONNHAP.THANHTIEN%TYPE
)
IS 
BEGIN
  INSERT INTO HR.CT_HOADONNHAP
  VALUES(P_MAHDN, P_MATB, P_TENTHIETBI, P_DONGIANHAP, P_SLNHAP, P_THANHTIEN);
  COMMIT;
END;
/

--Thu tuc UPDATE CT_HOADONNHAP
CREATE OR REPLACE PROCEDURE UPDATE_CT_HOADONNHAP
(
  P_MAHDN IN HR.CT_HOADONNHAP.MAHDN%TYPE,
  P_MATB IN HR.CT_HOADONNHAP.MATB%TYPE,
  P_TENTHIETBI IN HR.CT_HOADONNHAP.TENTHIETBI%TYPE,
  P_DONGIANHAP IN HR.CT_HOADONNHAP.DONGIANHAP%TYPE,
  P_SLNHAP IN HR.CT_HOADONNHAP.SLNHAP%TYPE,
  P_THANHTIEN IN HR.CT_HOADONNHAP.THANHTIEN%TYPE
)
IS
BEGIN
  UPDATE HR.CT_HOADONNHAP
  SET MAHDN = P_MAHDN, MATB = P_MATB, TENTHIETBI = P_TENTHIETBI,
      DONGIANHAP = P_DONGIANHAP, SLNHAP = P_SLNHAP, THANHTIEN = P_THANHTIEN
  WHERE MAHDN = P_MAHDN AND MATB = P_MATB;
  COMMIT;
END;
/

--Thu tuc DELETE CT_HOADONBAN
CREATE OR REPLACE PROCEDURE DELETE_CT_HOADONNHAP
(P_MAHDN IN HR.CT_HOADONNHAP.MAHDN%TYPE, P_MATB IN HR.CT_HOADONNHAP.MATB%TYPE)
IS
BEGIN
  DELETE HR.CT_HOADONNHAP WHERE MAHDN = P_MAHDN AND MATB = P_MATB;
  COMMIT;
END;
/

--Thu tuc tim kiem khach hang
CREATE OR REPLACE PROCEDURE SEARCH_KHACHHANG
(P_KHACHHANG IN VARCHAR2, OUT_CURSOR_KH OUT SYS_REFCURSOR)
AS
BEGIN
  OPEN OUT_CURSOR_KH FOR
  SELECT * FROM HR.KHACHHANG
  WHERE MAKH LIKE ('%'||P_KHACHHANG||'%') OR 
        TENKH LIKE ('%'||P_KHACHHANG||'%');
END;
/

--Thu tuc tim kiem san pham
CREATE OR REPLACE PROCEDURE SEARCH_THIETBI
(P_SANPHAM IN VARCHAR2, OUT_CURSOR_SP OUT SYS_REFCURSOR)
AS
BEGIN
  OPEN OUT_CURSOR_SP FOR
  SELECT * FROM HR.THIETBI
  WHERE MATB LIKE ('%'||P_SANPHAM||'%') OR 
        TENTB LIKE ('%'||P_SANPHAM||'%');
END;
/

---------------------------------------TRIGGER KIEM TRA-----------------------------------------------
--TRIGGER Cap nhat lai giam SOLUONG o bang THIETBI khi them vao bang CT_HOADONBAN
  CREATE OR REPLACE TRIGGER TRIGG_GIAM_SOLUONG
  AFTER INSERT OR UPDATE OF MAHDB OR UPDATE OF SLBAN OR DELETE 
  ON HR.CT_HOADONBAN FOR EACH ROW
  BEGIN
  IF DELETING THEN UPDATE HR.THIETBI SET SOLUONG=SOLUONG+:OLD.SLBAN WHERE MATB=:OLD.MATB;
  ELSIF INSERTING THEN 
  UPDATE HR.THIETBI SET SOLUONG=SOLUONG-:NEW.SLBAN WHERE MATB=:NEW.MATB;
  ELSIF UPDATING THEN
  UPDATE HR.THIETBI SET SOLUONG=SOLUONG-:NEW.SLBAN WHERE MATB=:NEW.MATB;
  UPDATE HR.THIETBI SET SOLUONG=SOLUONG+:OLD.SLBAN WHERE MATB=:OLD.MATB;
  END IF;
  END;
  
  
--TRIGGER Cap nhat lai tang SOLUONG o bang THIETBI khi them vao bang CT_HOADONNHAP
  CREATE OR REPLACE TRIGGER TRIGG_TANG_SOLUONG
  AFTER INSERT OR UPDATE OF MAHDN OR UPDATE OF SLNHAP OR DELETE 
  ON HR.CT_HOADONNHAP FOR EACH ROW
  BEGIN
  IF DELETING THEN UPDATE HR.THIETBI SET SOLUONG=SOLUONG-:OLD.SLNHAP WHERE MATB=:OLD.MATB;
  ELSIF INSERTING THEN 
  UPDATE HR.THIETBI SET SOLUONG=SOLUONG+:NEW.SLNHAP WHERE MATB=:NEW.MATB;
  ELSIF UPDATING THEN
  UPDATE HR.THIETBI SET SOLUONG=SOLUONG+:NEW.SLNHAP WHERE MATB=:NEW.MATB;
  UPDATE HR.THIETBI SET SOLUONG=SOLUONG-:OLD.SLNHAP WHERE MATB=:OLD.MATB;
  END IF;
  END;
  
--Trigger cap nhat tong tien cua hoa don ban
CREATE OR REPLACE TRIGGER UPDATE_TONGTIEN_HDB
AFTER INSERT OR UPDATE OF SLBAN OR DELETE ON HR.CT_HOADONBAN
FOR EACH ROW
DECLARE
  T_TONGTIEN_N HR.HOADONBAN.TONGTIEN%TYPE;
  T_TONGTIEN_O HR.HOADONBAN.TONGTIEN%TYPE;
BEGIN
  T_TONGTIEN_N=: NEW.DONGIABAN * NEW.SLBAN;
  T_TONGTIEN_O=: NEW.DONGIABAN * NEW.SLBAN;
  IF DELETETING THEN UPDATE HR.HOADONBAN
    SET TONGTIEN = TONGTIEN - T_TONGTIEN_O
    WHERE MAHDB=:OLD.MAHDB;
  ELSIF INSERTING THEN UPDATE HR.HOADONBAN
    SET TONGTIEN = TONGTIEN + T_TONGTIEN_N
    WHERE MAHDB=:NEW.MAHDB;
  ELSIF UPDATING THEN UPDATE HR.HOADONBAN
    SET TONGTIEN = TONGTIEN - T_TONGTIEN_O + T_TONGTIEN_N
    WHERE MAHDB=:NEW.MAHDB AND MAHDB=:OLD.MAHDB;
  END IF;
END;

--Update tong tien hoa don ban
UPDATE HR.HOADONBAN 
SET TONGTIEN = (SELECT SUM(THANHTIEN) FROM HR.CT_HOADONBAN WHERE MAHDB='HDB005') 
FROM HR.HOADONBAN HD, HR.CT_HOADONBAN CTHD 
WHERE HD.MAHDB = CTHD.MAHDB AND HD.MAHDB='HDB005'

---- Xoa cac table
DROP TABLE CT_HOADONNHAP;
DROP TABLE CT_HOADONBAN;
DROP TABLE HOADONBAN;
DROP TABLE HOADONNHAP;
DROP TABLE THIETBI;
DROP TABLE THUONGHIEU;
DROP TABLE NHACUNGCAP;
DROP TABLE NHANVIEN;
DROP TABLE KHACHHANG;
commit;
